# fly.toml app configuration file generated for doo on 2023-07-22T02:43:51+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "doo"
primary_region = "syd"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
